from selenium.webdriver.common.by import By


class PublicLoc:
    """公共组件"""


class LoginPageLoc:
    """登录"""
    email = (By.ID, "email")
    password = (By.ID, "password")
    sign_in = (By.ID, "js-btnSubmit")


class HomePageLoc:
    """首页"""

    # 标题栏
    user_info = (By.CSS_SELECTOR, "a.siteHeader_userAccountLink")
    sign_in = (By.CSS_SELECTOR, "a.siteHeader_userLinkLogin")
    my_fav = (By.XPATH, "//header/div[2]/div[3]/div[1]/div[1]/div[1]/p/a")
    cart = (By.XPATH, "//header/div[2]/div[3]/div[3]/a[2]/p")
    # 用户信息菜单
    my_order = (By.XPATH, "//ul/li[2]/a")
    my_tickets = (By.XPATH, "//ul/li[3]/a")
    my_message = (By.XPATH, "//ul/li[4]/a")
    my_wallet = (By.XPATH, "//ul/li[5]/a")
    my_points = (By.XPATH, "//ul/li[6]/a")
    my_profile = (By.XPATH, "//ul/li[7]/a")
    my_coupon = (By.XPATH, "//ul/li[8]/a")
    logout = (By.CLASS_NAME, "js-logout")
    # 弹窗
    new_user_pop = (By.CLASS_NAME, "newUserPop")
    close_pop = (By.CLASS_NAME, "layui-layer-setwin")


class UserInfoPageLoc:
    """用户信息页"""
    goods_images = (By.CSS_SELECTOR, "a.orderItem_thumb")
    goods_names = (By.CSS_SELECTOR, "a.orderItem_title")


class GoodsInfoPageLoc:
    """商品详情页"""

    qty = (By.CLASS_NAME, "compInputNumber_input")
    num_plus = (By.CLASS_NAME, "compInputNumber_reduce")
    num_reduce = (By.CLASS_NAME, "compInputNumber_plus")
    buy_button = (By.XPATH, "//*[@class='goodsIntro_btnWrap js-buyBtnWrap']/a[2]")
    paypal_button = (By.XPATH, "//*[@class='goodsIntro_btnWrap js-buyBtnWrap']/a[3]")


class PlaceInfoPageLoc:
    """订单确认页"""

    # place_button = (By.XPATH, "//a[@class='ckOl_totalBtn btn middle strong']")
    # place_button = (By.XPATH, "//a[contains(text(),'Place Now')]")
    place_button = (By.XPATH, "//a[@class='ckOl_totalBtn btn middle strong']")


# class PaymentInfoPageLoc:
#     """收银台"""
#
#     pay_button = (By.XPATH, "//*[@class='placeOrder btn block toPayBtn']")
#     pay_currencyselect = (By.XPATH, "//*[@class='currency_select']")
#     pay_currencyconfirm = (By.XPATH, "//*[@class='currency_select']/option[2]")
#     Wallet_ele = (By.XPATH, "//span[contains(text(),'My Wallet')]")
#     Wallet_input = (By.XPATH, "//*[@placeholder='Please enter the Wallet password']")
#     paypal_src = (By.XPATH, '//*[@src="https://uidesign.gbtcdn.com/check_out/paypal.png?impolicy==true"]')
#     creditcard_src = (By.XPATH, '//*[@src="https://uidesign.zafcdn.com/ZF/image/z_promo/20190418_9281/discover.png"]')
#     creditcard_holder = (By.XPATH, "//*[@placeholder='Card Holder']")
#     creditcard_Number = (By.XPATH, "//*[@placeholder='Card Number']")
#     creditcard_Code = (By.XPATH, "//*[@placeholder='Security Code']")
#     creditcard_mouth = (By.XPATH, '//*[@curchannel="CREDITCARD"]/div[2]/div/select')
#     creditcard_day = (By.XPATH, '//*[@curchannel="CREDITCARD"]/div[3]/div/select')
#     ebanxinstalment_src = (By.XPATH, '//*[@src="https://uidesign.zafcdn.com/ZF/image/z_promo/20190418_9281/elo.png"]/../../em[1]/img')
#     ebanxinstalment_installments = (By.XPATH, '//*[@class="formList_select installments"]/option[2]')
#     ebanxinstalment_CPF = (By.XPATH, "//*[@placeholder='CPF']")
#     ebanxinstalment_Titular = (By.XPATH, "//*[@placeholder='Titular do cartão']")
#     ebanxinstalment_Nmero = (By.XPATH, "//*[@placeholder='Número de cartão']")
#     ebanxinstalment_Cdigo = (By.XPATH, "//*[@placeholder='Código de segurança']")
#     ebanxinstalment_Month = (By.XPATH, '//*[@name="expirationMonth"]')
#     ebanxinstalment_Year = (By.XPATH, '//*[@name="expirationYear"]')
#     TRCC_src = (By.XPATH, '//*[@src="https://uidesign.gbtcdn.com/GB/images/others/tr_installment_logo.png"]')
#     TRCC_Number = (By.XPATH, "//*[@curchannel='PayU_TRCC']/div[1]/div/input")
#     TRCC_Installments = (By.XPATH, '//*[@src="https://uidesign.gbtcdn.com/GB/images/others/tr_installment_logo.png"]')
#     TRCC_select = (By.XPATH, "//*[@class='paychannel checked']/dd/div/div[2]/div/select/option[4]")
#     TRCC_Month = (By.XPATH, "//*[@curchannel='PayU_TRCC']/div[3]/div/select")
#     TRCC_Year = (By.XPATH, "//*[@curchannel='PayU_TRCC']/div[4]/div/select")
#     TRCC_code = (By.XPATH, "//*[@curchannel='PayU_TRCC']/div[5]/div/input")
#     TRCC_holder = (By.XPATH, "//*[@curchannel='PayU_TRCC']/div[6]/div/input")
#     BKM_src = (By.XPATH, '//*[@src="https://css.gbtcdn.com/imagecache/GB3/images/domeimg/pay_method/PayU_BKM.png"]')
#     BKM_select = (By.XPATH, "//*[@class='currency_select']")
#     BKM_select1 = (By.XPATH, "//*[@class='currency_select']/option[2]")
#     boleto_src = (By.XPATH, '//*[@src="https://uidesign.gbtcdn.com/check_out/beloto.png"]')
#     boleto_cpf = (By.XPATH, '//*[@curchannel="BOLETO"]/div[1]/div[1]/div/input[1]')
#     boleto_select = (By.XPATH, "//*[@class='currency_select']")
#     boleto_select1 = (By.XPATH, "//*[@class='currency_select']/option[2]")
#     PTMB_src = (By.XPATH, '//*[@src="https://uidesign.gbtcdn.com/check_out/Mutibanco_m.png?impolicy=high"]')
#     PTMB_select = (By.XPATH, "//*[@class='currency_select']")
#     PTMB_select1 = (By.XPATH, "//*[@class='currency_select']/option[2]")
#     WP24_src = (By.XPATH, '//*[@src="https://icss1.gearbest.com/imagecache/GB2/images/domeimg/pay_method/przelewy24.jpg"]')
#     WP24_select = (By.XPATH, "//*[@class='currency_select']")
#     WP24_select1 = (By.XPATH, "//*[@class='currency_select']/option[2]")
#     INNB_src = (By.XPATH, '//*[@src="https://uidesign.gbtcdn.com/check_out/NetBanking.png?impolicy=high?01"]')
#     INNB_select = (By.XPATH, "//*[@class='currency_select']")
#     INNB_select1 = (By.XPATH, "//*[@class='currency_select']/option[2]")
#     ideal_src = (By.XPATH, '//*[@src="https://icss1.gearbest.com/imagecache/GB2/images/domeimg/pay_method/ideal.png"]')
#     ideal_Bank = (By.XPATH, '//*[@name="IssueBank"]')
#     ideal_select = (By.XPATH, "//*[@class='currency_select']")
#     ideal_select1 = (By.XPATH, "//*[@class='currency_select']/option[2]")
#     MXCC_src = (By.XPATH, '//*[@src="https://uidesign.gbtcdn.com/GB/image/z_promo/20190516_9912/MasterCard_debit.png"]')
#     MXCC_titular = (By.XPATH, "//*[@placeholder='titular de la tarjeta']")
#     MXCC_Nmero = (By.XPATH, "//*[@placeholder='Número de tarjeta']")
#     MXCC_mouth = (By.XPATH, "//*[@name='expirationMonth']")
#     MXCC_year = (By.XPATH, "//*[@name='expirationYear']")
#     MXCC_Cdigo = (By.XPATH, "//*[@placeholder='Código de seguridad']")
#     OXXO_src = (By.XPATH, '//*[@src="https://icss1.gearbest.com/imagecache/GB2/images/domeimg/pay_method/oxxo.jpg"]')
#     BankTransfer_src = (By.XPATH, '//*[@src="https://uidesign.gbtcdn.com/GB/image/banner/20180404_2970/GC_banktransfer.jpg"]')
#     WPQIWI_src = (By.XPATH, '//*[@src="https://icss1.gearbest.com/imagecache/GB2/images/domeimg/pay_method/qiwi.png"]')
#     WPQIWI_phone = (By.XPATH, "//*[@placeholder='Mobile phone']")
#     yandexmoney_src = (By.XPATH, '//*[@src="https://css.gbtcdn.com/imagecache/GB3/images/domeimg/pay_method/en/yandex_money.jpg"]')
#     RUCT_src = (By.XPATH, '//*[@src="https://css.gbtcdn.com/imagecache/GB3/images/domeimg/pay_method/ADN_RUCT.jpg"]')
#     IDATM_src = (By.XPATH, '//*[@src="https://css.zafcdn.com/imagecache/ZF_V2/images/domeimg/pay_method/ADN_IDATM.jpg"]')
#     IDACS_src = (By.XPATH, '//*[@src="https://css.zafcdn.com/imagecache/ZF_V2/images/domeimg/pay_method/ADN_IDATM.jpg"]')
#     PSE_src = (By.XPATH, '//*[@src="http://www.wearesellers.com/uploads/answer/20170120/6d9cdbfcc224e1fc7dec9d401c5abbfd.jpg"]')
#     PSE_pseBankCode = (By.XPATH, '//*[@name="pseBankCode"]')
#     PSE_documentType = (By.XPATH, '//*[@name="documentType"]')
#     PSE_tel = (By.XPATH, '//*[@type="tel"]')
#     AGPC_src = (By.XPATH, '//*[@src="https://uidesign.gbtcdn.com/GB/image/app/20180623_3877/22.png?impolicy=high"]')
#     AGPC_select = (By.XPATH, '//*[@curchannel="EBX_AGPC"]/div[2]/div/select')
#     AGPC_tel = (By.XPATH, '//*[@type="tel"]')
#     BEBC_src = (By.XPATH, '//*[@src="https://uidesign.gbtcdn.com/check_out/Bancontact_b.png"]')
#     BEBC_number = (By.XPATH, '//*[@curchannel="ADN_BEBC"]/div[1]/div/input')
#     BEBC_month = (By.XPATH, '//*[@curchannel="ADN_BEBC"]/div[2]/div/select')
#     BEBC_year = (By.XPATH, '//*[@curchannel="ADN_BEBC"]/div[3]/div/select')
#     BEBC_holder = (By.XPATH, '//*[@curchannel="ADN_BEBC"]/div[4]/div/input')
#     EPS_src = (By.XPATH, '//*[@src="https://icss1.gearbest.com/imagecache/GB2/images/domeimg/pay_method/eps.jpg"]')
#     SOFORT_src = (By.XPATH, '//*[@src="https://uidesign.gbtcdn.com/GB/images/others/check_out/sofort.png?02"]')
#     DEGP_src = (By.XPATH, '//*[@src="https://icss1.gearbest.com/imagecache/GB2/images/domeimg/pay_method/giropay.jpg"]')
#     LipaPay_src = (By.XPATH, '//*[@src="https://uidesign.gbtcdn.com/check_out/Lipapay.png?impolicy=ture"]')
#     MYOB_src = (By.XPATH, '//*[@src="https://uidesign.gbtcdn.com/check_out/ADN_MYOB.png?impolicy=high"]')
#     THOB_src = (By.XPATH, '//*[@src="https://css.zafcdn.com/imagecache/ZF_V2/images/domeimg/pay_method/ADN_THOB.jpg"]')
#     BANK_TRANSFER_src = (By.XPATH, '//*[@src="https://icss1.gearbest.com/imagecache/GB2/images/domeimg/pay_method/WiredTransfer.jpg"]')
#     WESTERN_src = (By.XPATH, '//*[@src="https://icss1.gearbest.com/imagecache/GB2/images/domeimg/pay_method/WesternUnion.jpg"]')
#     EBX_SVPG_src = (By.XPATH, '//*[@src="https://uidesign.gbtcdn.com/check_out/Servipag.png?impolicy=high"]')
#     EBX_SVPG_doc = (By.XPATH, "//*[@curchannel='EBX_SVPG']/div[1]/div/select")
#     EBX_SVPG_number = (By.XPATH, "//*[@curchannel='EBX_SVPG']/div[2]/div/input")
#     ADN_TRSP_src = (By.XPATH, '//*[@src="https://uidesign.gbtcdn.com/check_out/Trustpay.png?impolicy==true"]')
#     ADN_TRSP_issuerId = (By.XPATH, "//*[@name='issuerId']")
#     Postepay_src = (By.XPATH, '//*[@src="https://uidesign.gbtcdn.com/GB/images/others/check_out/postepay.jpg"]')
#     PagoEfectivo_src = (By.XPATH, '//*[@src="https://icss1.gearbest.com/imagecache/GB2/images/domeimg/pay_method/pagoefectivo.png"]')
#     SQ_ESCC1_src = (By.XPATH, '//*[@src="https://uidesign.gbtcdn.com/check_out/SQ_ESCC1.png"]')
#     poli_src = (By.XPATH, '//*[@src="https://uidesign.gbtcdn.com/check_out/poli_m.png?impolicy=high"]')
#     Webmoney_src = (By.XPATH, '//*[@src="https://icss1.gearbest.com/imagecache/GB2/images/domeimg/pay_method/webmoney.jpg"]')
#     # WPG_Pay_src = (By.XPATH, '//*[@src="https://uidesign.gbtcdn.com/check_out/Gpay.png?03"]')
#     WPG_Pay_src = (By.XPATH, '//span[@paychannel="WPG_Pay"]')

class PaymentInfoPageLoc:
    """收银台"""

    pay_button = (By.XPATH, "//*[@class='placeOrder btn block toPayBtn']")
    pay_currencyselect = (By.XPATH, "//*[@class='currency_select']")
    pay_currencyconfirm = (By.XPATH, "//*[@class='currency_select']/option[2]")
    Wallet_ele = (By.XPATH, "//span[contains(text(),'My Wallet')]")
    Wallet_input = (By.XPATH, "//*[@placeholder='Please enter the Wallet password']")
    paypal_src = (By.XPATH, '//span[@paychannel="PAYPAL"]')
    creditcard_src = (By.XPATH, '//*[@src="https://uidesign.zafcdn.com/ZF/image/z_promo/20190418_9281/discover.png"]')
    creditcard_holder = (By.XPATH, "//*[@placeholder='Card Holder']")
    creditcard_Number = (By.XPATH, "//*[@placeholder='Card Number']")
    creditcard_Code = (By.XPATH, "//*[@placeholder='Security Code']")
    creditcard_mouth = (By.XPATH, '//*[@curchannel="CREDITCARD"]/div[2]/div/select')
    creditcard_day = (By.XPATH, '//*[@curchannel="CREDITCARD"]/div[3]/div/select')
    ebanxinstalment_src = (By.XPATH, '//span[@paychannel="ebanxinstalment"]')
    ebanxinstalment_installments = (By.XPATH, '//*[@class="formList_select installments"]/option[2]')
    ebanxinstalment_CPF = (By.XPATH, "//*[@placeholder='CPF']")
    ebanxinstalment_Titular = (By.XPATH, "//*[@placeholder='Titular do cartão']")
    ebanxinstalment_Nmero = (By.XPATH, "//*[@placeholder='Número de cartão']")
    ebanxinstalment_Cdigo = (By.XPATH, "//*[@placeholder='Código de segurança']")
    ebanxinstalment_Month = (By.XPATH, '//*[@name="expirationMonth"]')
    ebanxinstalment_Year = (By.XPATH, '//*[@name="expirationYear"]')
    TRCC_src = (By.XPATH, '//span[@paychannel="PayU_TRCC"]')
    TRCC_Number = (By.XPATH, "//*[@curchannel='PayU_TRCC']/div[1]/div/input")
    TRCC_Installments = (By.XPATH, '//*[@src="https://uidesign.gbtcdn.com/GB/images/others/tr_installment_logo.png"]')
    TRCC_select = (By.XPATH, "//*[@class='paychannel checked']/dd/div/div[2]/div/select/option[4]")
    TRCC_Month = (By.XPATH, "//*[@curchannel='PayU_TRCC']/div[3]/div/select")
    TRCC_Year = (By.XPATH, "//*[@curchannel='PayU_TRCC']/div[4]/div/select")
    TRCC_code = (By.XPATH, "//*[@curchannel='PayU_TRCC']/div[5]/div/input")
    TRCC_holder = (By.XPATH, "//*[@curchannel='PayU_TRCC']/div[6]/div/input")
    BKM_src = (By.XPATH, '//span[@paychannel="PayU_BKM"]')
    BKM_select = (By.XPATH, "//*[@class='currency_select']")
    BKM_select1 = (By.XPATH, "//*[@class='currency_select']/option[2]")
    boleto_src = (By.XPATH, '//span[@paychannel="BOLETO"]')
    boleto_cpf = (By.XPATH, '//*[@curchannel="BOLETO"]/div[1]/div[1]/div/input[1]')
    boleto_select = (By.XPATH, "//*[@class='currency_select']")
    boleto_select1 = (By.XPATH, "//*[@class='currency_select']/option[2]")
    PTMB_src = (By.XPATH, '//span[@paychannel="ADN_PTMB"]')
    PTMB_select = (By.XPATH, "//*[@class='currency_select']")
    PTMB_select1 = (By.XPATH, "//*[@class='currency_select']/option[2]")
    WP_PTMB_src = (By.XPATH, '//span[@paychannel="WP_PTMB"]')
    WP_PTMB_select = (By.XPATH, "//*[@class='currency_select']")
    WP_PTMB_select1 = (By.XPATH, "//*[@class='currency_select']/option[2]")
    WP24_src = (By.XPATH, '//span[@paychannel="WP_P24"]')
    WP24_select = (By.XPATH, "//*[@class='currency_select']")
    WP24_select1 = (By.XPATH, "//*[@class='currency_select']/option[2]")
    INNB_src = (By.XPATH, '//span[@paychannel="PayU_INNB"]')
    INNB_select = (By.XPATH, "//*[@class='currency_select']")
    INNB_select1 = (By.XPATH, "//*[@class='currency_select']/option[2]")
    ideal_src = (By.XPATH, '//span[@paychannel="ideal"]')
    ideal_Bank = (By.XPATH, '//*[@name="IssueBank"]')
    ideal_select = (By.XPATH, "//*[@class='currency_select']")
    ideal_select1 = (By.XPATH, "//*[@class='currency_select']/option[2]")
    MXCC_src = (By.XPATH, '//span[@paychannel="EBX_MXCC"]')
    MXCC_titular = (By.XPATH, "//*[@placeholder='titular de la tarjeta']")
    MXCC_Nmero = (By.XPATH, "//*[@placeholder='Número de tarjeta']")
    MXCC_mouth = (By.XPATH, "//*[@name='expirationMonth']")
    MXCC_year = (By.XPATH, "//*[@name='expirationYear']")
    MXCC_Cdigo = (By.XPATH, "//*[@placeholder='Código de seguridad']")
    OXXO_src = (By.XPATH, '//span[@paychannel="OXXO"]')
    BankTransfer_src = (By.XPATH, '//*[@src="https://uidesign.gbtcdn.com/GB/image/banner/20180404_2970/GC_banktransfer.jpg"]')
    WPQIWI_src = (By.XPATH, '//span[@paychannel="WP_QIWI"]')
    WPQIWI_phone = (By.XPATH, "//*[@placeholder='Mobile phone']")
    yandexmoney_src = (By.XPATH, '//span[@paychannel="yandex_money"]')
    RUCT_src = (By.XPATH, '//span[@paychannel="ADN_RUCT"]')
    IDATM_src = (By.XPATH, '//span[@paychannel="ADN_IDATM"]')
    IDACS_src = (By.XPATH, '//span[@paychannel="ADN_IDACS"]')
    PSE_src = (By.XPATH, '//span[@paychannel="PSE"]')
    PSE_pseBankCode = (By.XPATH, '//*[@name="pseBankCode"]')
    PSE_documentType = (By.XPATH, '//*[@name="documentType"]')
    PSE_tel = (By.XPATH, '//*[@type="tel"]')
    AGPC_src = (By.XPATH, '//span[@paychannel="EBX_AGPC"]')
    AGPC_select = (By.XPATH, '//*[@curchannel="EBX_AGPC"]/div[2]/div/select')
    AGPC_tel = (By.XPATH, '//*[@type="tel"]')
    BEBC_src = (By.XPATH, '//span[@paychannel="ADN_BEBC"]')
    BEBC_number = (By.XPATH, '//*[@curchannel="ADN_BEBC"]/div[1]/div/input')
    BEBC_month = (By.XPATH, '//*[@curchannel="ADN_BEBC"]/div[2]/div/select')
    BEBC_year = (By.XPATH, '//*[@curchannel="ADN_BEBC"]/div[3]/div/select')
    BEBC_holder = (By.XPATH, '//*[@curchannel="ADN_BEBC"]/div[4]/div/input')
    EPS_src = (By.XPATH, '//span[@paychannel="ADN_EPS"]')
    SOFORT_src = (By.XPATH, '//span[@paychannel="SOFORT_SSL"]')
    ADN_DEGP_src = (By.XPATH, '//span[@paychannel="ADN_DEGP"]')
    WP_DEGP_src = (By.XPATH, '//span[@paychannel="WP_DEGP"]')
    LipaPay_src = (By.XPATH, '//span[@paychannel="LipaPay"]')
    MYOB_src = (By.XPATH, '//span[@paychannel="ADN_MYOB"]')
    THOB_src = (By.XPATH, '//span[@paychannel="ADN_THOB"]')
    BANK_TRANSFER_src = (By.XPATH, '//span[@paychannel="BANK_TRANSFER"]')
    WESTERN_src = (By.XPATH, '//span[@paychannel="WESTERN"]')
    EBX_SVPG_src = (By.XPATH, '//span[@paychannel="EBX_SVPG"]')
    EBX_SVPG_doc = (By.XPATH, "//*[@curchannel='EBX_SVPG']/div[1]/div/select")
    EBX_SVPG_number = (By.XPATH, "//*[@curchannel='EBX_SVPG']/div[2]/div/input")
    ADN_TRSP_src = (By.XPATH, '//span[@paychannel="ADN_TRSP"]')
    ADN_TRSP_issuerId = (By.XPATH, "//*[@name='issuerId']")
    Postepay_src = (By.XPATH, '//span[@paychannel="ADN_TRSP"]')
    PagoEfectivo_src = (By.XPATH, '//span[@paychannel="PagoEfectivo"]')
    SQ_ESCC1_src = (By.XPATH, '//span[@paychannel="SQ_ESCC1"]')
    SQ_ESCC2_src = (By.XPATH, '//span[@paychannel="SQ_ESCC2"]')
    poli_src = (By.XPATH, '//span[@paychannel="poli"]')
    Webmoney_src = (By.XPATH, '//span[@paychannel="webmoney"]')
    WPG_Pay_src = (By.XPATH, '//span[@paychannel="WPG_Pay"]')
    DLC_Boleto_src = (By.XPATH, '//span[@paychannel="DLC_Boleto"]')
    # DLC_Boleto_cpf = (By.XPATH, '//*[@class="cpfWrapper"]/div[1]/div')
    DLC_Boleto_cpf = (By.XPATH, '//*[@class="formList_phone_select cpfSelect"]/input[1]')
    WP_SOFORT_SW_src = (By.XPATH, '//span[@paychannel="WP_SOFORT_SW"]')
    PayU_UPI_src = (By.XPATH, '//span[@paychannel="PayU_UPI"]')
    DGPAY_PHdp_src = (By.XPATH, '//span[@paychannel="DGPAY_PHdp"]')






class ThirdInfoPageLoc:
    """支付第三方"""
    mainSubmit = (By.XPATH, "//*[@id='mainSubmit']")
    GC_password = (By.XPATH, "//*[@type='password']")
    GC_Entry = (By.XPATH, "//*[@name='UsernamePasswordEntry']")
    BKM_loginBtn = (By.XPATH, "//*[@id='loginBtn']")
    BKM_username = (By.ID, "username")
    BKM_passwordPwd = (By.ID, "passwordPwd")
    BKM_submit = (By.XPATH, '//*[@type="submit"]')
    BKM_otp = (By.ID, "otp")
    BKM_installmentselect = (By.XPATH, '//*[@id="installment-select"]/tbody/tr[3]/td[2]')
    BKM_submitcard = (By.XPATH, '//*[@id="submit-card"]')
    PTMB_shopperEmail = (By.XPATH, "//*[@id='multibanco.shopperEmail']")
    PTMB_mainSubmit = (By.XPATH, "//*[@id='mainSubmit']")
    WP24_contiun = (By.XPATH, '//*[@src="/images/buttons/makepayment.gif"]')
    INNB_successButton = (By.XPATH, "//*[@id='successButton']")
    ideal_submit = (By.XPATH, "//*[@type='submit']")
    WPQIWI_makepayment = (By.XPATH, "//*[@src='/images/buttons/makepayment.gif']")
    yandexmoney_button = (By.XPATH, "//*[@class='button button_size_m button_theme_action payment-contract__pay-button i-bem button_js_inited']")
    yandexmoney_cardNumber = (By.XPATH, "//*[@id='cardNumber']")
    yandexmoney_MM = (By.XPATH, "//*[@placeholder='MM']")
    yandexmoney_YY = (By.XPATH, "//*[@placeholder='YY']")
    yandexmoney_cardCvc = (By.XPATH, "//*[@name='skr_cardCvc']")
    yandexmoney_html = (By.XPATH, "/html/body/div[2]/div/div/div[4]/a")
    RUCT_authorised = (By.XPATH, '//*[@class="caret authorised"]')
    IDATM_mainSubmit = (By.XPATH, "//*[@id='mainSubmit']")
    IDATM_firstName = (By.XPATH, "//*[@id='doku_permata_lite_atm.shopper.firstName']")
    IDATM_lastName = (By.XPATH, "//*[@id='doku_permata_lite_atm.shopper.lastName']")
    IDATM_shopperEmail = (By.XPATH, "//*[@id='doku_permata_lite_atm.shopperEmail']")
    IDATM_footerB = (By.XPATH, "//*[@class='footerB']")
    IDACS_mainSubmit = (By.XPATH, "//*[@id='mainSubmit']")
    IDACS_firstName = (By.XPATH, "//*[@id='doku_alfamart.shopper.firstName']")
    IDACS_lastName = (By.XPATH, "//*[@id='doku_alfamart.shopper.lastName']")
    IDACS_shopperEmail = (By.XPATH, "//*[@id='doku_alfamart.shopperEmail']")
    IDACS_footerB = (By.XPATH, "//*[@class='footerB']")
    PSE_YES = (By.XPATH, "//a[contains(text(),'Authorized = YES')]")
    BEBC_username = (By.XPATH, '//*[@id="username"]')
    BEBC_password = (By.XPATH, '//*[@id="password"]')
    BEBC_submit = (By.XPATH, '//*[@type="submit"]')
    EPS_authorised = (By.XPATH, '//*[@class="caret authorised"]')
    SOFORT_makepayment = (By.XPATH, '//*[@src="/images/buttons/makepayment.gif"]')

    DEGP_bic_selection = (By.XPATH, '//*[@id="giropay.bic-selection"]')
    # DEGP_Bank = (By.XPATH, '//*[@data1-bankname="Test DE Bank"]')
    DEGP_Bank = (By.XPATH, "//*[contains(text(),'Test DE Bank')]")

    DEGP_mainSubmit = (By.XPATH, '//*[@id="mainSubmit"]')
    DEGP_sc = (By.XPATH, '//*[@name="sc"]')
    DEGP_extensionSc = (By.XPATH, '//*[@name="extensionSc"]')
    DEGP_customerName1 = (By.XPATH, '//*[@name="customerName1"]')
    DEGP_customerIBAN = (By.XPATH, '//*[@name="customerIBAN"]')
    DEGP_submit = (By.XPATH, '//*[@type="submit"]')
    LipaPay_left = (By.XPATH, '//*[@class="pay-type-left"]/em[1]')
    LipaPay_email = (By.XPATH, '//*[@class="email"]')

    LipaPay_btn = (By.XPATH, '//*[@class="pay-btn"]')
    LipaPay_dialogMain = (By.XPATH, '//*[@id="dialogMain"]/div/a')

    LipaPay_shopping_btn = (By.XPATH, '//a[@class="return-to-merchant-url"]')
    MYOB_authorised = (By.XPATH, '//*[@class="caret authorised"]')
    Postepay_pc_orderinf = (By.XPATH, "//*[@class='pc_orderinf']/dl[1]/dd")

    SQ_ESCC1_primary = (By.XPATH, "//*[@class='button-component primary']")
    SQ_ESCC1_given_names = (By.XPATH, "//*[@name='given_names']")
    SQ_ESCC1_surnames = (By.XPATH, "//*[@name='surnames']")
    SQ_ESCC1_date_of_birth = (By.XPATH, "//*[@name='date_of_birth']")
    SQ_ESCC1_nin = (By.XPATH, "//*[@name='nin']")
    SQ_ESCC1_mobile_phone = (By.XPATH, "//*[@name='mobile_phone']")
    SQ_ESCC1_terms_accepted = (By.XPATH, "//*[@for='terms_accepted']")
    SQ_ESCC1_validation_code = (By.XPATH, "//*[@name='validation_code']")
    SQ_ESCC1_component = (By.XPATH, "//*[@class='card-selector-component']")
    poli_continue = (By.XPATH, "//*[@name='continue']")
    poli_Username= (By.XPATH, "//*[@name='Username']")
    poli_Password = (By.XPATH, "//*[@name='Password']")
    poli_LoginButton = (By.XPATH, "//*[@name='LoginButton']/../button")
    poli_textContinue = (By.XPATH, "//*[contains(text(),'Continue')]")
    poli_primarybutton = (By.XPATH, "//*[@class='button stp-button primary-button']")
    poli_ConfirmButton = (By.XPATH, "//*[@name='ConfirmButton']/../button")
    WPG_Pay_email = (By.XPATH, "//*[@type='email']")
    PayU_UPI_upiVpa = (By.XPATH, "//input[@id='upiVpa']")
    PayU_UPI_button = (By.XPATH, "//*[@id='citrusUpiPayButton']")






