log:
    file_name: test.log
    backup: 5
    console_level: INFO
    file_level: DEBUG
    pattern: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
mail:
    server: smtp.qq.com
    port: 465
    sender: 583241254@qq.com
    password: qffmtutgoxbtbfff
    receiver: 583241254@qq.com      # 以;号隔开多个收件人
    title: 测试结果
GB:
    GBURL: https://www.gearbest.net/
    GBloginURL: https://login.gearbest.net/m-users-a-sign.htm?type=1
    UA: jiangjiahao
    GBusername: 583241254@qq.com
    GBpassword: abc456456

ObsLoginUrl: 'http://www.obs-gb.com/'
PcLoginUrl:
goodsUrl:
ObsAccount:
    userName: zhangwei
    password: zhang1wei





payMapping:  # 支付方式对应国家收货地址
    - payPal: united states
    - credit: a
    - BKM: b


payMethods:  # 各种表单信息
    payPal:
        - cardnuber:
        - scode:


walletPWD: 123456



